=== xzchaoo/LearningNotes/Other/XML/client1/bin/5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://example.com/5"
	elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="http://example.com/5">
   <xs:element name="bookInfo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="bookSort" type="xs:string" maxOccurs="unbounded"/>
                <xs:element name="book" type="tns:bookType" maxOccurs="unbounded"/>            
            </xs:sequence>        
        </xs:complexType>
        <xs:key name="sortKey">
            <xs:selector xpath="bookSort"/>
            <xs:field xpath="."/>
        </xs:key>
        <xs:keyref refer="tns:sortKey" name="sortKeyRef">
            <xs:selector xpath="book"></xs:selector>
            <xs:field xpath="@type"></xs:field>
        </xs:keyref>
        <xs:unique name="maneUnique">
            <xs:selector xpath="book"></xs:selector>
            <xs:field xpath="name"></xs:field>
        </xs:unique>
    </xs:element>
    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="quantity" type="xs:integer"/>
            <xs:element name="price" type="xs:decimal"/>
        </xs:sequence>    
        <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== xzchaoo/LearningNotes/Other/XML/client1/bin/5.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookInfo xmlns="http://example.com/5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://example.com/5 5.xsd">
	<bookSort>2sadasdasd</bookSort>
	<book type="technology">
		<name>XML Schema应用</name>
		<quantity>2</quantity>
		<price>20</price>
	</book>
	<book type="noveld">
		<name>疯狂程序员</name>
		<quantity>3</quantity>
		<price>15</price>
	</book>
	<book type="history">
		<name>三国志</name>
		<quantity>1</quantity>
		<price>30</price>
	</book>

</bookInfo>
