=== xzchaoo/LearningNotes/Other/XML/client1/src/xzc/jaxb/4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.cnblogs.com"
	xmlns="http://www.cnblogs.com">
	<xs:element name="bookInfo">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="book" type="bookType" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
		<xs:key name="sortKey">
			<xs:selector xpath="bookSort" />
			<xs:field xpath="." />
		</xs:key>
		<xs:keyref refer="sortKey" name="sortKeyRef">
			<xs:selector xpath="book"></xs:selector>
			<xs:field xpath="@type"></xs:field>
		</xs:keyref>
		<xs:unique name="maneUnique">
			<xs:selector xpath="book"></xs:selector>
			<xs:field xpath="name"></xs:field>
		</xs:unique>
	</xs:element>
	<xs:complexType name="bookType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="quantity" type="xs:integer" />
			<xs:element name="price" type="xs:decimal" />
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" />
	</xs:complexType>
</xs:schema>

=== xzchaoo/LearningNotes/Other/XML/client1/src/xzc/jaxb/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookInfo xmlns="http://www.cnblogs.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cnblogs.com 4.xsd">
	<bookSort>technology</bookSort>
	<bookSort>novel</bookSort>
	<bookSort>history</bookSort>
	<book type="technology">
		<name>XML Schema应用</name>
		<quantity>2</quantity>
		<price>20</price>
	</book>
	<book type="novel">
		<name>疯狂程序员</name>
		<quantity>3</quantity>
		<price>15</price>
	</book>
	<book type="history">
		<name>三国志</name>
		<quantity>1</quantity>
		<price>30</price>
	</book>
</bookInfo>
